/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL._hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
   public void testChanged() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> result = new ArrayList<>(Arrays.asList(1, 2, 3, 5));
      assertEquals(App.change(array, 4, 5), result );
    }

    @Test
    public void testNoChange() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertEquals(App.change(array, 5, 10),array);
    }

    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertEquals(App.change(array, 1,4),array);
    }

    @Test
    public void testNull() {
      assertNull(App.change(null, 1,1));
    }

}
